// Generated by CoffeeScript 2.5.1
(function() {
  global.navigator = {
    userAgent: 'summat'
  };

  exports.ymaTest = {
    "Should make an app": function(test) {
      var app;
      app = require('../dist/index')('myApp');
      test.equal(app.appName, 'myApp', 'Name check');
      return test.done();
    },
    "Should make a scope": function(test) {
      var app, scope;
      app = require('../dist/index')('myApp');
      scope = app.Scope();
      test.ok(scope.$id);
      return test.done();
    },
    "Should make a component": function(test) {
      var app;
      app = require('../dist/index')('myApp');
      app.component('myComponent', function(app) {
        return function(scope, elem, props) {
          return console.log('controller');
        };
      });
      test.equal(typeof (app.$getComponents()['MYCOMPONENT']), 'function');
      return test.done();
    }
  };

}).call(this);
