// Generated by CoffeeScript 2.5.1
(function() {
  var app;

  global.navigator = {
    userAgent: 'summat'
  };

  app = require('../dist/index')('myApp');

  exports.ymaTest = {
    test1: function(test) {
      test.equal(app.appName, 'myApp', 'Name check');
      return test.done();
    }
  };

}).call(this);
