// Generated by CoffeeScript 2.5.1
(function() {
  var Yma, scopeToUpdate;

  Yma = require('../../../dist/index');

  window.app = Yma('myApp');

  console.log('window app', window.app);

  scopeToUpdate = null;

  window.app.component('app', function(app) {
    return {
      controller: function(scope) {
        scopeToUpdate = scope;
        return scope.testVar = 'buddy';
      }
    };
  });

  window.doUpdate = function() {
    return scopeToUpdate.$update({
      testVar: 'maggie'
    });
  };

}).call(this);
